### PR TITLE
support Colima along with Docker Desktop

### PR DESCRIPTION
**Pull request by kakysha**

### CODE REVIEW

**Comment by blaise-io** [comment]
Hey @kakysha, thanks for contributing!

I don't want to explicitly support Colima because it's supposed to be drop-in and it's still in early development. I would accept a pull request that supports any drop-in container runtime. Can you change this PR a little?

1. In `MainMenu.swift`, use `canPlay = Process.runCommand("docker").terminationStatus == 0`
2. Same in `AppDelegate.application`
3. Revert `PATH` in `Process.runcommand`. 

Can you confirm Ace Link would still support Colima this way?

**Comment by kakysha** [comment]
`PATH` is actually a second improvement to support `docker`-cli installed via MacPorts, as in my case. 
I also see some code to start Docker Desktop bundle, what should we do with that in case we have another runtime?
I'd opt-in to not touch it as Person who replaced the runtime should know how to start it manually

**Comment by blaise-io** [comment]
> `PATH` is actually a second improvement to support `docker`-cli installed via MacPorts, as in my case. 

Thanks for the explanation, let's leave that in.

>  I also see some code to start Docker Desktop bundle, what should we do with that in case we have another runtime?
>  I'd opt-in to not touch it as Person who replaced the runtime should know how to start it manually

I agree.

**Comment by blaise-io** [comment]
I'll create a new release later this week.

**Comment by blaise-io** [comment]
And thank you!

**Pull request merged**
